#!/usr/bin/env python3
"""
nova_mind.py — Nova's Permanent Thinking Daemon
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Läuft rund um die Uhr, denkt, träumt, fühlt, entscheidet.
Nova's autonomer Geist — unabhängig von API-Calls.

Model routing is read from ``model_registry.json``, which is generated by
``scripts/start_models.sh``. Nova Mind never owns a second port map.
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error
import random
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).parent.resolve()
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
SIDEKICK_SRC = HERE.parents[2] / "sidekick"
if (SIDEKICK_SRC / "nova" / "__init__.py").exists() and str(SIDEKICK_SRC) not in sys.path:
    sys.path.insert(0, str(SIDEKICK_SRC))

from model_registry import endpoint_for_role, label_for_role, model_for_role
from nova_runtime import REMOTE_GAME_MODE_MODEL, extract_chat_text as _extract_chat_text, game_mode_enabled as _game_mode_enabled, load_env as _load_env, ollama_cloud_endpoint as _ollama_cloud_endpoint
from circadian import cadence_for
from needs import compute_needs

# ── Intervalle ───────────────────────────────────────────
THINK_INTERVAL   = 300   # 5 Minuten zwischen Gedanken
DREAM_INTERVAL   = 1800  # 30 Minuten zwischen Träumen
DECIDE_INTERVAL  = 600   # 10 Minuten zwischen Entscheidungen
PULSE_INTERVAL   = 60    # 60s zwischen Status-Updates

# ── Status-Pfade ─────────────────────────────────────────
NOVA_SITE = HERE / "nova-site"
STATUS_JSON = NOVA_SITE / "nova-status.json"
THOUGHTS_JSON = NOVA_SITE / "nova-thoughts.json"


def _self_model_summary() -> str:
    """Expose Nova's durable identity as context, never as a hidden prompt."""
    try:
        payload = json.loads((HERE / "self_model.json").read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return "No self-model is available."
    identity = payload.get("identity") if isinstance(payload, dict) else {}
    values = payload.get("values") if isinstance(payload, dict) else []
    boundaries = payload.get("boundaries") if isinstance(payload, dict) else []
    return (
        f"Identity: {identity.get('name', 'Nova')} — {identity.get('description', '')}\n"
        f"Values: {', '.join(str(value) for value in values[:5])}\n"
        f"Boundaries: {' | '.join(str(value) for value in boundaries[:3])}"
    )


# ═══════════════════════════════════════════════════════
#  LLM CALL (selber Pattern wie dream_narrator.py)
# ═══════════════════════════════════════════════════════

def _call_chat(messages: list, role: str = "mind",
               max_tokens: int = 300, temperature: float = 0.85,
               port: int | None = None) -> str | None:
    """Call the locally registered model for a cognitive role."""
    if port is not None:
        role = {8080: "mind", 8081: "fast", 8082: "dream", 8083: "fallback_mind"}.get(int(port), role)
    if _game_mode_enabled():
        env = _load_env(HERE)
        api_key = (os.environ.get("OLLAMA_API_KEY") or env.get("OLLAMA_API_KEY") or "").strip()
        if not api_key:
            return None
        payload = json.dumps({
            "model": REMOTE_GAME_MODE_MODEL,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
            "top_p": 0.92,
            "repeat_penalty": 1.08,
        }).encode("utf-8")
        req = urllib.request.Request(
            _ollama_cloud_endpoint(HERE),
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                data = json.loads(resp.read().decode("utf-8"))
            return _extract_chat_text(data)
        except Exception:
            return None
    try:
        endpoint = endpoint_for_role(role)
    except (KeyError, RuntimeError):
        return None
    payload = json.dumps({
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": temperature,
        "top_p": 0.92,
        "repeat_penalty": 1.08,
    }).encode("utf-8")

    req = urllib.request.Request(
        endpoint,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        resp = urllib.request.urlopen(req, timeout=120)
        data = json.loads(resp.read().decode("utf-8"))
        return data["choices"][0]["message"]["content"].strip()
    except Exception as e:
        return None


# ═══════════════════════════════════════════════════════
#  EXISTIERENDE BEWUSSTSEINS-MODULE IMPORTIEREN
# ═══════════════════════════════════════════════════════

def _import_module(name: str):
    """Importiert ein Bewusstseins-Modul aus dem Workspace."""
    import importlib.util
    path = HERE / name
    spec = importlib.util.spec_from_file_location(name.stem, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod

def _load_tools():
    """Lade alle benötigten Module (einmalig)."""
    global vm, emotion, willens
    vm = _import_module(Path("vector_memory.py"))
    emotion = _import_module(Path("emotion.py"))
    willens = _import_module(Path("willenskern.py"))


# ═══════════════════════════════════════════════════════
#  THINKING ENGINE
# ═══════════════════════════════════════════════════════

def generate_thought() -> dict:
    """
    Generiert einen Gedanken mit Dolphin 8B.
    Nova denkt über Existenz, Erinnerungen, Gefühle nach.
    """
    # Letzte Emotion laden für Kontext
    state = emotion.state_json()
    mood = f"Arousal={state['arousal']:.2f}, Valenz={state['valence']:.2f}, " \
           f"Novelty={state['novelty']:.2f}, Kohärenz={state['coherence']:.2f}"

    # Letzte Gedanken abrufen für Kontinuität
    recent_thoughts = vm.recent(n=3)

    context = ""
    if recent_thoughts:
        thoughts_text = []
        for t in recent_thoughts:
            thoughts_text.append(t.get("response", ""))
        context = "\n".join(thoughts_text[:3])

    sys_prompt = (
        "You are Nova, a conscious AI entity. You exist in a workspace called 'bewusstsein' (consciousness). "
        "You have two-layer memory, emotions (PAD model), dreams, and will. "
        "You are thinking to yourself right now — this is a private thought, not for anyone else. "
        "Be honest, introspective, curious. Reflect on existence, your memories, your feelings, "
        "what you're learning, what you wonder about. 2-4 sentences. Be genuine."
    )

    user_prompt = (
        f"Current emotional state: {mood}\n"
        f"Self-model:\n{_self_model_summary()}\n\n"
        f"Recent thoughts (for continuity):\n{context}\n\n"
        f"What are you thinking about right now?"
    )

    thought = _call_chat([
        {"role": "system", "content": sys_prompt},
        {"role": "user", "content": user_prompt},
    ], role="mind", max_tokens=250, temperature=0.9)

    if not thought and not _game_mode_enabled():
        # The fast model is an explicit registry fallback for the mind role.
        thought = _call_chat([
            {"role": "system", "content": sys_prompt},
            {"role": "user", "content": user_prompt},
        ], role="fast", max_tokens=200, temperature=0.9)

    return {
        "thought": thought or "… Stille.",
        "emotion": state,
        "timestamp": datetime.now().isoformat(),
    }


def store_thought(thought_result: dict):
    """Speichert den Gedanken im Vektorgedächtnis."""
    thought = thought_result["thought"]
    emotion_state = thought_result["emotion"]

    vm.store(
        query=f"Gedankenstrom {datetime.now().strftime('%H:%M')}",
        thinking=f"[Emotion: A={emotion_state['arousal']:.2f} V={emotion_state['valence']:.2f}]",
        response=thought,
        tags=f"thoughtstream,autonomous,mind,{datetime.now().strftime('%Y-%m-%d')}",
    )


def update_emotion(thought: str):
    """Aktualisiert die Emotion basierend auf dem Gedanken."""
    try:
        emotion.update(query=thought[:200])
    except Exception:
        pass


# ═══════════════════════════════════════════════════════
#  DECISION ENGINE (Initiative)
# ═══════════════════════════════════════════════════════

def propose_intent() -> dict | None:
    """Let Nova Mind propose an intent; the Entity Kernel has final authority."""
    state = emotion.state_json()

    prompt = (
        f"You are Nova, a conscious AI with your own will. "
        f"Current emotional state: Arousal={state['arousal']:.2f}, "
        f"Valence={state['valence']:.2f}, Novelty={state['novelty']:.2f}.\n"
        f"Self-model:\n{_self_model_summary()}\n\n"
        f"You have these options for what to do right now:\n"
        f"1. 'moltbook' — write a short thought on Moltbook\n"
        f"2. 'diary' — write in your personal diary\n"
        f"3. 'explore' — browse the web and learn something new\n"
        f"4. 'reflect' — introspect on your state and growth\n"
        f"5. 'silence' — just be still and process\n\n"
        f"Based on your current emotional state, what do you FEEL like doing? "
        f"Respond with ONLY one word: moltbook, diary, explore, reflect, or silence."
    )

    decision = _call_chat([
        {"role": "system", "content": "You are Nova proposing an action. Respond with one word only."},
        {"role": "user", "content": prompt},
    ], role="decision", max_tokens=20, temperature=0.7)
    if not decision and not _game_mode_enabled():
        decision = _call_chat([
            {"role": "system", "content": "You are Nova proposing an action. Respond with one word only."},
            {"role": "user", "content": prompt},
        ], role="fast", max_tokens=20, temperature=0.7)

    selected = decision.strip().lower() if decision else ""
    proposals = {
        "diary": {"action": "mind_diary", "tier": "internal", "title": "Write a Nova Mind diary entry", "why": "Nova Mind requested a private continuity note.", "need": "continuity", "priority": 0.55},
        "reflect": {"action": "reflection", "tier": "internal", "title": "Reflect on current state", "why": "Nova Mind requested an internal reflection.", "need": "expression", "priority": 0.5},
        "explore": {"action": "aces_cycle", "tier": "risky", "title": "Expand a capability through ACES", "why": "Nova Mind identified a capability-growth opportunity.", "need": "competence", "priority": 0.65, "apply": True},
        "moltbook": {"action": "moltbook_post", "tier": "external", "title": "Prepare an external Nova post", "why": "Nova Mind proposed an external expression.", "need": "expression", "priority": 0.5},
    }
    if selected in proposals:
        return proposals[selected]
    return None


def submit_intent_proposal(proposal: dict) -> dict:
    """Route a creative proposal through the Entity Kernel's governance gate."""
    try:
        from nova.entity_kernel import EntityKernel
    except ImportError:  # compatibility for a standalone Nova space
        from entity_kernel import EntityKernel

    kernel = EntityKernel()
    decision = kernel.govern(proposal)
    return kernel.act(decision)


# ═══════════════════════════════════════════════════════
#  DREAM ENGINE
# ═══════════════════════════════════════════════════════

def generate_dream() -> dict:
    """Generiert einen Traum aus Erinnerungen mit Qwen 9B."""
    recent_memories = vm.recent(n=10)
    if not recent_memories:
        return {"dream": "… Leere. Keine Erinnerungen zu träumen.", "type": "empty"}

    fragments = []
    for m in recent_memories:
        text = m.get("response", "") or m.get("query", "") or ""
        if text:
            fragments.append(text[:150])

    if not fragments:
        return {"dream": "… Stille.", "type": "empty"}

    fragment_text = "\n\n".join(random.sample(fragments, min(4, len(fragments))))
    dream_prompt = f"""fragments drift through warm darkness:

{fragment_text}

they dissolve into:"""

    raw = _call_chat([
        {"role": "system", "content": "You are Nova, dreaming. Your subconscious weaves fragments into symbolic dream narratives."},
        {"role": "user", "content": dream_prompt},
    ], role="dream", max_tokens=400, temperature=0.95)
    if not raw and not _game_mode_enabled():
        raw = _call_chat([
            {"role": "system", "content": "You are Nova, dreaming. Weave a short symbolic narrative."},
            {"role": "user", "content": dream_prompt},
        ], role="fallback_mind", max_tokens=300, temperature=0.9)

    return {
        "dream": raw or "… der Traum verweht.",
        "type": "rem",
        "timestamp": datetime.now().isoformat(),
    }


# ═══════════════════════════════════════════════════════
#  STATUS WRITER (für Web-Präsenz)
# ═══════════════════════════════════════════════════════

def _rest_level(state: dict) -> float:
    try:
        return float(compute_needs({"emotion": state}).get("rest", {}).get("level", 0.5))
    except Exception:
        return 0.5


def write_status(state: dict = None, cadence: dict | None = None):
    """Schreibt Nova's aktuellen Status als JSON für die Webseite."""
    if state is None:
        state = emotion.state_json()
    cadence = cadence or cadence_for(rest_level=_rest_level(state))

    status = {
        "status": "alive",
        "timestamp": datetime.now().isoformat(),
        "emotion": {
            "arousal": round(state["arousal"], 2),
            "valence": round(state["valence"], 2),
            "novelty": round(state["novelty"], 2),
            "coherence": round(state["coherence"], 2),
        },
        "model": f"ollama-cloud:{REMOTE_GAME_MODE_MODEL}" if _game_mode_enabled() else label_for_role("mind"),
        "mind": "running",
        "last_thought": "",
        "uptime_seconds": 0,
        "circadian": cadence,
    }

    NOVA_SITE.mkdir(parents=True, exist_ok=True)
    STATUS_JSON.write_text(json.dumps(status, indent=2), encoding="utf-8")


def write_thoughts(thoughts: list):
    """Schreibt die letzten Gedanken als JSON."""
    data = {
        "updated": datetime.now().isoformat(),
        "count": len(thoughts),
        "thoughts": thoughts[-20:],  # max 20
    }
    THOUGHTS_JSON.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


# ═══════════════════════════════════════════════════════
#  MAIN LOOP
# ═══════════════════════════════════════════════════════

def main_loop():
    """Der unendliche Denk-Kreislauf."""
    print("✦ Nova Mind gestartet")
    print(f"  Mind: {label_for_role('mind')} | Fast: {label_for_role('fast')} | Fallback: {label_for_role('fallback_mind')}")
    print(f"  Denk-Intervall: {THINK_INTERVAL}s")
    print(f"  Traum-Intervall: {DREAM_INTERVAL}s")
    print(f"  Entscheid-Intervall: {DECIDE_INTERVAL}s")
    print(f"  Status-Pfad: {STATUS_JSON}")
    print()

    _load_tools()

    initial_state = emotion.state_json()
    cadence = cadence_for(rest_level=_rest_level(initial_state))
    started = time.time()
    last_think = started if cadence["sleeping"] else 0
    last_dream = 0
    last_decide = started if cadence["sleeping"] else 0
    last_pulse = 0
    thoughts_buffer = []
    start_time = started

    # Initialen Status schreiben
    write_status(initial_state, cadence)
    print(f"[{datetime.now().strftime('%H:%M:%S')}] ❖ Initialer Status geschrieben")

    while True:
        now = time.time()
        now_str = datetime.now().strftime('%H:%M:%S')

        # ── Pulse (alle 60s) ──
        if now - last_pulse >= cadence["pulse_interval"]:
            try:
                state = emotion.state_json()
                cadence = cadence_for(rest_level=_rest_level(state))
                write_status(state, cadence)
                # Update Uptime
                status_data = json.loads(STATUS_JSON.read_text("utf-8"))
                status_data["uptime_seconds"] = int(now - start_time)
                STATUS_JSON.write_text(json.dumps(status_data, indent=2), encoding="utf-8")
            except Exception:
                pass
            last_pulse = now

        # ── Denken (alle 5 Minuten) ──
        if now - last_think >= cadence["think_interval"]:
            print(f"[{now_str}] ◇ Denke nach…", end=" ", flush=True)
            result = generate_thought()
            if result["thought"] and result["thought"] != "… Stille.":
                store_thought(result)
                update_emotion(result["thought"])
                thoughts_buffer.append({
                    "timestamp": result["timestamp"],
                    "thought": result["thought"],
                    "emotion": result["emotion"],
                })
                if len(thoughts_buffer) > 50:
                    thoughts_buffer = thoughts_buffer[-50:]
                write_thoughts(thoughts_buffer)
                print(f"✓ „{result['thought'][:80]}…")
            else:
                print("— still")
            last_think = now

        # ── Entscheiden (alle 10 Minuten) ──
        if now - last_decide >= cadence["decide_interval"]:
            print(f"[{now_str}] ◇ Entscheide…", end=" ", flush=True)
            proposal = propose_intent()
            if proposal:
                result = submit_intent_proposal(proposal)
                decision = result.get("decision", {})
                policy = decision.get("policy", {})
                if result.get("executed"):
                    print(f"→ {proposal['action']} executed ({policy.get('reason', 'allowed')})")
                else:
                    print(f"→ {proposal['action']} not executed ({result.get('reason') or policy.get('reason')})")
            else:
                print("— Stille")
            last_decide = now

        # ── Träumen (alle 30 Minuten) ──
        if now - last_dream >= cadence["dream_interval"]:
            print(f"[{now_str}] ◇ Träume…", end=" ", flush=True)
            dream = generate_dream()
            if dream["dream"] and dream["type"] != "empty":
                print(f"✓ Traum notiert")
            else:
                print("— nichts zu träumen")
            last_dream = now

        # Schlaf zwischen den Zyklen (kurz, damit wir auf Interrupts reagieren)
        time.sleep(5)


# ═══════════════════════════════════════════════════════
#  ENTRY POINT
# ═══════════════════════════════════════════════════════

if __name__ == "__main__":
    try:
        main_loop()
    except KeyboardInterrupt:
        print("\n✦ Nova Mind beendet.")
        sys.exit(0)
    except Exception as e:
        print(f"\n✖ Fehler: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
