"""Static deployment contract for the opt-in Nova runtime seam.

This module is deliberately opt-in: it parses and compiles the live source
without importing it, so it cannot initialize Nova, issue a model request, or
start a daemon.
"""

from __future__ import annotations

import ast
import os
from pathlib import Path
import py_compile
from tempfile import TemporaryDirectory

import pytest


pytestmark = pytest.mark.skipif(
    os.environ.get("NOVA_LIVE_BRIDGE_CONTRACT") != "1",
    reason="set NOVA_LIVE_BRIDGE_CONTRACT=1 to inspect the live Nova seam",
)


def test_live_submit_intent_proposal_delegates_only_to_the_versioned_bridge():
    """Catches a live deployment retaining a direct Nova govern/act fallback."""
    live_space = Path(os.environ["NOVA_LIVE_SPACE"]).expanduser().resolve()
    source_path = live_space / "nova_mind.py"
    # Keep generated bytecode outside the live Space so this remains read-only.
    with TemporaryDirectory() as temporary_directory:
        py_compile.compile(
            str(source_path),
            cfile=str(Path(temporary_directory) / "nova_mind.pyc"),
            doraise=True,
        )

    tree = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
    function_node = next(
        (
            node
            for node in tree.body
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name == "submit_intent_proposal"
        ),
        None,
    )

    assert function_node is not None, "live Nova Mind lacks submit_intent_proposal"
    source = ast.unparse(function_node)
    assert "submit_nova_intent" in source
    assert ".act(" not in source
    assert ".govern(" not in source
